### ISSUE TITLE
Script

### ISSUE THREAD

**Issue by MeteoJeremy** [mhacarthur/IMERG_processing#1]
Hello.

Can you share me some script to convert data half hourly to hourly of IMERG data to plot the diurnal cycle of the precipitation?. Thanks

kind regards,
Jeremy

**Comment by mhacarthur** [comment]
the directory jupyter/preprocessing has a half_hour_to_hour_01x01.ipynb, for export half hour to hour data. In relation to diurnal cycle. I still don't have a code for that task

**Comment by MeteoJeremy** [comment]
Hello. 

Thanks for sharing this code.

Do you have some script in python for download the data half hourly that you can share me?. Thanks

**Comment by mhacarthur** [comment]
Yes, in directory Jupyter/Download you can use download_half_hour.ipynb

**Comment by MeteoJeremy** [comment]
Thanks for sharing it. If I have some questions. I can let you know. Thanks

**Comment by MeteoJeremy** [comment]
Hi.  Can you share with me some script to  plot data IMERG data hourly to a temporal series of  my point interest 3.14° S , 59.99°W ? 

I am interested in 00UTC 15 FEB 2014 - 00UTC 26FE2014.

Thanks

**Comment by MeteoJeremy** [comment]
Hello, 

I downloaded data of precipitation from ERA5, the variable is total precipitation is metres. How can I convert it mm/ hours and I can get values instantaneously every hour?

Also, I have IMERG files of precipitation accumulated in 30 minutes . How can I have precipitation accumulated in one hour?


Thanks

**Comment by mhacarthur** [comment]
if yo download IMERG Hourly data, and the data is in meters. You precipitation is m/hour, same to daily (m/day). Because one file is a acummulated for this time.

You can add two files (half hour) that make up 1 hour, example: 18:00 + 18:30 -> 18:00 m/hour
